basePath: /api
definitions:
  github_com_Brotiger_per-painted_poker-backend_internal_module_auth_request.Login:
    properties:
      password:
        example: password
        type: string
      username:
        example: username
        type: string
    required:
    - password
    - username
    type: object
  github_com_Brotiger_per-painted_poker-backend_internal_module_auth_request.Refresh:
    properties:
      refreshToken:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuYXV0aDAuY29tLyIsImF1ZCI6Imh0dHBzOi8vYXBpLmV4YW1wbGUuY29tL2NhbGFuZGFyL3YxLyIsInN1YiI6InVzcl8xMjMiLCJpYXQiOjE0NTg3ODU3OTYsImV4cCI6MTQ1ODg3MjE5Nn0.CA7eaHjIHz5NxeIJoFK9krqaeZrPLwmMmgI_XiQiIkQ
        type: string
    type: object
  github_com_Brotiger_per-painted_poker-backend_internal_module_auth_response.Token:
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuYXV0aDAuY29tLyIsImF1ZCI6Imh0dHBzOi8vYXBpLmV4YW1wbGUuY29tL2NhbGFuZGFyL3YxLyIsInN1YiI6InVzcl8xMjMiLCJpYXQiOjE0NTg3ODU3OTYsImV4cCI6MTQ1ODg3MjE5Nn0.CA7eaHjIHz5NxeIJoFK9krqaeZrPLwmMmgI_XiQiIkQ
        type: string
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuYXV0aDAuY29tLyIsImF1ZCI6Imh0dHBzOi8vYXBpLmV4YW1wbGUuY29tL2NhbGFuZGFyL3YxLyIsInN1YiI6InVzcl8xMjMiLCJpYXQiOjE0NTg3ODU3OTYsImV4cCI6MTQ1ODg3MjE5Nn0.CA7eaHjIHz5NxeIJoFK9krqaeZrPLwmMmgI_XiQiIkQ
        type: string
    type: object
  github_com_Brotiger_per-painted_poker-backend_internal_shared_response.Error400:
    properties:
      errors: {}
      message:
        type: string
    type: object
  github_com_Brotiger_per-painted_poker-backend_internal_shared_response.Error401:
    properties:
      message:
        type: string
    type: object
  response.Game:
    properties:
      count_players:
        example: 3
        type: integer
      id:
        example: 507f1f77bcf86cd799439011
        type: string
      max_players:
        example: 4
        type: integer
      title:
        example: test
        type: string
      with_password:
        example: true
        type: boolean
    type: object
  response.GameList:
    properties:
      games:
        items:
          $ref: '#/definitions/response.Game'
        type: array
      total:
        example: 100
        type: integer
    type: object
info:
  contact: {}
  title: Core API
paths:
  /auth/login:
    post:
      parameters:
      - description: Body params
        in: body
        name: request
        schema:
          $ref: '#/definitions/github_com_Brotiger_per-painted_poker-backend_internal_module_auth_request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ.
          schema:
            $ref: '#/definitions/github_com_Brotiger_per-painted_poker-backend_internal_module_auth_response.Token'
        "400":
          description: Не валидный запрос.
          schema:
            $ref: '#/definitions/github_com_Brotiger_per-painted_poker-backend_internal_shared_response.Error400'
        "401":
          description: Не верное имя пользователя или пароль.
          schema:
            $ref: '#/definitions/github_com_Brotiger_per-painted_poker-backend_internal_shared_response.Error401'
        "500":
          description: Ошибка сервера.
      security:
      - Authorization: []
      summary: Авторизация
      tags:
      - Auth
  /auth/logout:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ.
        "500":
          description: Ошибка сервера.
      security:
      - Authorization: []
      summary: Выход
      tags:
      - Auth
  /auth/refresh:
    post:
      parameters:
      - description: Body params
        in: body
        name: request
        schema:
          $ref: '#/definitions/github_com_Brotiger_per-painted_poker-backend_internal_module_auth_request.Refresh'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ.
          schema:
            $ref: '#/definitions/github_com_Brotiger_per-painted_poker-backend_internal_module_auth_response.Token'
        "400":
          description: Не валидный запрос.
          schema:
            $ref: '#/definitions/github_com_Brotiger_per-painted_poker-backend_internal_shared_response.Error400'
        "401":
          description: Неверный или просроченный токен обновления.
          schema:
            $ref: '#/definitions/github_com_Brotiger_per-painted_poker-backend_internal_shared_response.Error401'
        "500":
          description: Ошибка сервера.
      security:
      - Authorization: []
      summary: Обновление токена
      tags:
      - Auth
  /game/list:
    get:
      parameters:
      - example: 0
        in: query
        minimum: 0
        name: from
        required: true
        type: integer
      - example: test
        in: query
        name: name
        type: string
      - example: 20
        in: query
        minimum: 0
        name: size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ.
          schema:
            $ref: '#/definitions/response.GameList'
        "400":
          description: Не валидный запрос.
          schema:
            $ref: '#/definitions/github_com_Brotiger_per-painted_poker-backend_internal_shared_response.Error400'
        "401":
          description: Не верное имя пользователя или пароль.
          schema:
            $ref: '#/definitions/github_com_Brotiger_per-painted_poker-backend_internal_shared_response.Error401'
        "500":
          description: Ошибка сервера.
      security:
      - Authorization: []
      summary: Игра
      tags:
      - Game
securityDefinitions:
  Authorization:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
